version: "0.2"
ignorePaths: []
language: en,es
dictionaryDefinitions: []
dictionaries: []
words:
  - cupertino
  - flutter_lints
  - JSOB
  - nullable
  - uuid
ignoreWords: []
import: []
enabledFileTypes:
  json: false
