name: watered_plants_ota_labs
description: "A app to remind me watering my plants."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  flutter:
    sdk: flutter
  intl: ^0.19.0
  nested: ^1.0.0
  provider: ^6.1.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
